version: '3.7'

services:
  web:
    container_name: btre_container
    networks:
      - btre_net
    tty: true
    build: ./app
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    container_name: postgres_container
    networks:
      - btre_net
    ports:
      - 5432:5432
    tty: true
    image: postgres:9.6-alpine
    environment:
      POSTGRES_PASSWORD: password1234
    volumes:
      - postgres_data:/var/lib/postgresql/data/
networks:
  btre_net:
volumes:
  postgres_data:
