# pull official base image
FROM ubuntu:18.04

# set work directory
WORKDIR /usr/src/pyapps

# set environment variables
ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# upgrade to latest files
#RUN apt update && apt upgrade

RUN apt-get update && apt-get install \
  -y --no-install-recommends python3 python3-virtualenv

ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m virtualenv --python=/usr/bin/python3 $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# install python 3, postgres and nginx
RUN apt-get update && apt-get install -y \
    curl \
    python3-pip\
    python3-dev \
    libpq-dev \
    postgresql \
    postgresql-contrib \
    nginx

#install requirements
COPY ./requirements4.txt /usr/src/pyapps/requirements4.txt
RUN pip install -r requirements4.txt

# copy project files
COPY . /usr/src/pyapps/

#CMD systemctl start postgres
#CMD service postgresql start
RUN service postgresql start
