# pull official base image
#FROM ubuntu:18.04
FROM python:3.6-stretch

# set work directory
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install psycopg2 dependencies

RUN apt-get update && apt-get install -y \
    curl \
    python3-pip\
    python3-dev \
    libpq-dev \
    postgresql \
    postgresql-contrib \
    nginx

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements4.txt /usr/src/app/requirements4.txt
RUN pip install -r requirements4.txt

# copy project
COPY . /usr/src/app/

# enable postgres
# CMD systemctl start postgres
