# Generated by Django 2.2.6 on 2019-12-10 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developer',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='developer',
            name='last_name',
        ),
    ]
